cloud_provider: vagrant
 
cloud_providers:
  vagrant:
    # Rubber assumes every cloud provider has configuration.  Vagrant really doesn't need anything, but until the core
    # of Rubber handles that, just set a dummy value.
    dummy: true
    # allow rubber to connect directly to instance in addition to use through vagrant commands
    key_name: insecure_private_key
    key_file: "#{File.expand_path('~/.vagrant.d/insecure_private_key')}"
